### ISSUE TITLE
Create a user interface for the document search using Streamlit

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [sahil-sagwekar2652/semantic-search-demo#2]
Create a user interface which should include -

- [ ] File upload
- [ ] Verify if file is a `.pdf`
- [ ]  Text input for questions

**Comment by aindree-2005** [comment]
@sahil-sagwekar2652  I am still learning about Streamlit, but can I work on a portion of this issue?

**Comment by shashankk204** [comment]
@sahil-sagwekar2652  Sir can you Assign me this Issue I have made  UI for my team in SIH for ML project using Streamlit. So I have good experience in it

**Comment by sahil-sagwekar2652** [comment]
@aindree-2005 You can start working on this issue, I am assigning it to you.

**Comment by Adii0906** [comment]
can i work on it sir ?

**Comment by aindree-2005** [comment]
@sahil-sagwekar2652  I would like to be unassigned from this issue as I don't think I'm suitable for this task. I don't think I'll be able to focus on learning Streamlit well enough to finish it on time. Sorry for the inconvenience

**Comment by sahil-sagwekar2652** [comment]
Good call @aindree-2005 . Your accountability is appreciated. People just leave the issue unattended but you chose to reach out.

**Comment by sahil-sagwekar2652** [comment]
@shashankk204 would you like to work on this issue?

**Comment by shashankk204** [comment]
Yes sir,
I have written the code for the UI but I am unable integrate with existing project

**Comment by MiirzaBaig** [comment]
Can i work on this issue?
&can you also elaborate ?
